name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: 🔹 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔹 Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"  # Path to your HTML files (Root folder)
          output_location: ""  # Ensures no build step is expected
          app_build_command: ""  # Fully disables any build process
          skip_app_build: true  # Tells Azure to skip Oryx build