name: Deploy BigBank Frontend to Azure Static Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: 🔹 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔹 Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/public"  # ✅ Ensure correct path to index.html
          output_location: ""  # No build step needed
          skip_app_build: true  # ✅ Ensures Oryx does not try to build

      - name: 🔹 Output Live Website URL
        run: echo "🎉 Deployment successful! Visit your site at https://green-bay-0d49ad40f.6.azurestaticapps.net"