name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Deploy when pushing to main branch
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

      - name: 🔹 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔹 Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"  # Set this to your root directory
          api_location: ""  # Leave empty if not using an API
          output_location: ""  # No build step required
          app_build_command: ""  # Explicitly disable build step