name: Build and Deploy BigBank Frontend to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Ensure this matches your actual branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🔹 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔹 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure this matches your project requirements

      - name: 🔹 Install Dependencies (Only If Needed)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: 🔹 Build Static Files (Only If Needed)
        run: |
          if [ -f package.json ]; then
            npm run build
          fi

      - name: 🔹 Upload Build Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: public  # Ensure correct path to built files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 🔹 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔹 Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: public  # Ensure this contains index.html

      - name: 🔹 Deploy to Azure Static Web Apps
        id: deploy-to-webapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "public"  # Ensure this is correct
          output_location: ""  # No extra build step needed

      - name: 🔹 Output Live Website URL
        run: echo "🎉 Deployment successful! Visit your site at https://green-bay-0d49ad40f.6.azurestaticapps.net"