name: Trigger auto deployment for bigbank-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bigbank-frontend-AutoDeployTrigger-ee73dde7-b1ed-4783-9dc2-172f3cc511f5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BIGBANKFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BIGBANKFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BIGBANKFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Dockerfile-Frontend
          _dockerfilePathKey_: Dockerfile-Frontend
          registryUrl: bigbankacr123.azurecr.io
          registryUsername: ${{ secrets.BIGBANKFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BIGBANKFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: bigbank-frontend
          resourceGroup: rsbigbank
          imageToBuild: bigbankacr123.azurecr.io/bigbank-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


